### PR TITLE
feat(TextareaField): add character length counter

### PR DESCRIPTION
**Pull request by booc0mtaco**
### Summary:

- only shows up if max length is specified
- turns red if the default value is greater than allowed
- updates as you type
- currently no warning color as you approach limit
- by default textareas do not allow entry above maxlength
- but you can delete if somehow above maxlength
- field not in error state when above max length

### Test Plan:

- [x] Wrote [automated tests](https://czi.atlassian.net/wiki/x/Hbl1H)
- [ ] CI tests / new tests are not applicable
- [ ] Manually tested my changes, but I want to keep the details secret
- [x] Manually tested my changes, and here are the details:
  - review snapshot / chromatic changes

### CODE REVIEW

**Comment by booc0mtaco** [comment]
> I don't see a story that includes the character count, would it be worth capturing that state?

We apply character count when there's a `maxlength` specified, so stories [like this one](https://61313967cde49b003ae2a860-mtsuzqeqoy.chromatic.com/?path=/story/components-textareafield--with-a-max-length) will do the trick

**Comment by jeremiah-clothier** [comment]
> > I don't see a story that includes the character count, would it be worth capturing that state?
> 
> @jeremiah-clothier We apply character count when there's a `maxlength` specified, so stories [like this one](https://61313967cde49b003ae2a860-mtsuzqeqoy.chromatic.com/?path=/story/components-textareafield--with-a-max-length) will do the trick

Oh, I guess I was looking at the wrong chromatic build. I didn't realize their had been a few for the PR and the stories with that charater limit displayed were already accepted

**Review by jeremiah-clothier — APPROVED** [review]

**Review by jinlee93 — APPROVED** [review]
Any thoughts on having character count validation either as a recipe or a wrapping component to also be used on InputField?

**Comment by booc0mtaco** [comment]
@jinlee93 having the counter exist as a separate composable component isn't a bad idea. We can confer with design if any other fields like `InputField` could use this. I'm inclined to keep it as an integral part of `TextareaField` for now, since that's the only place in Figma that it lives currently.

**Comment by jinlee93** [comment]
> @jinlee93 having the counter exist as a separate composable component isn't a bad idea. We can confer with design if any other fields like `InputField` could use this. I'm inclined to keep it as an integral part of `TextareaField` for now, since that's the only place in Figma that it lives currently.

Makes sense to me, thanks

**Pull request merged**
