### PR TITLE
Remove bootstrap override hooks

### PR DESCRIPTION
**Pull request by ahuth**
EDS-850

Remove the `data-bootstrap-override` hooks. They're not needed anymore, because LP is staying on EDS v8.

### CODE REVIEW

**Comment by ahuth** [comment]
Thanks!

**Comment by booc0mtaco** [comment]
@ahuth Ah, i wish i had seen this sooner; I was hoping to keep any breaking changes out of the release this week to exercise some PR sorting. Luckily this one is breaking as a technicality (unless someone is sneakily using those attributes...)

**Comment by ahuth** [comment]
Got excited. Can revert, @booc0mtaco. Although definitely no-one using them in GST.

**Comment by booc0mtaco** [comment]
@ahuth It's all good; we can keep this in, and go to the next major. I wonder if the tooling knows how to handle a revert of a breaking change?

**Pull request merged**
