### PR TITLE
revert: "chore(icons): migrate icon architecture (#986)"

### PR DESCRIPTION
**Pull request by dierat**
### Summary:
This reverts commit 124dcbdcf86b5e5d303985fe583d68cf1b29da72.

In order to migrate the component APIs individually, I'm reverting this commit. I'll publish a new version without this change, cherry-pick it back, and publish again.

### Test Plan:
No type errors; icons in storybook are unchanged.

### CODE REVIEW

**Review by jinlee93 — APPROVED** [review]
I'm for the cherry picking strategy

**Comment by jinlee93** [comment]
Does this mean we need to update the pending api change prs with <SvgIcon>?

**Comment by dierat** [comment]
> Does this mean we need to update the pending api change prs with ?

When we have these changes split up into different publishes, we can update those PRs with the relevant package update. Since `Heading` and `Text` are on EDS together, those PRs will need to be merged. So there are 3 changes we need to make to the existing PRs: merge 2 PRs and update the EDS package in the remaining 2. Does that sound right?

**Comment by jinlee93** [comment]
> When we have these changes split up into different publishes, we can update those PRs with the relevant package update. Since Heading and Text are on EDS together, those PRs will need to be merged. So there are 3 changes we need to make to the existing PRs: merge 2 PRs and update the EDS package in the remaining 2. Does that sound right?

That sounds good to me!

**Pull request merged**
