### PR TITLE
fix(Avatar): adjust the tier 2 token used in size 'sm'

### PR DESCRIPTION
**Pull request by booc0mtaco**
### Test Plan:

- [x] Wrote [automated tests](https://czi.atlassian.net/wiki/x/Hbl1H)
- [ ] CI tests / new tests are not applicable
- [ ] Manually tested my changes, but I want to keep the details secret
- [x] Manually tested my changes, and here are the details:
  - verify change to snapshot as needed

### CODE REVIEW

**Comment by booc0mtaco** [comment]
Screenshot 2023-05-22 at 17 35 47

**Comment by booc0mtaco** [comment]
@jinlee93 looks like one of the filter tests is flaking out now?

**Review by jinlee93 — APPROVED** [review]

**Comment by jinlee93** [comment]
> @jinlee93 looks like one of the filter tests is flaking out now?

Thanks for tagging, seems like the button should have the tested name https://github.com/chanzuckerberg/edu-design-system/actions/runs/5051029277/jobs/9062428982#step:6:58 but not sure why it's failling

Will investigate in an other pr, but feel free to bypass merge

**Comment by booc0mtaco** [comment]
> Will investigate in an other pr, but feel free to bypass merge or add the skip if it's too flaky

re-ran and it passed, so will leave any adjustments to that followup PR!

**Pull request merged**
