### PR TITLE
chore: add beta information to component docstrings

### PR DESCRIPTION
**Pull request by dierat**
### Summary:
We've decided that we're going to all our pilot work branching directly off of `next`. That means in-progress components are going to ship with package publishes, be accessible from within `traject`, and show up in the EDS storybook. To communicate that these components are in-progress, I'm adding comments to the components to state that they're in-progress. (We used to do this with our components in EDSCandidates in `traject` as well.)

Since I'm messing with the component comments, I also added basic descriptions or todo comments, and I updated the plop template file as well.

#### In follow-up PRs, I will:
- utilize storybook badges to add a secondary method for communicating that these components are in beta
- add import examples to these component docstrings per our preferred documentation pattern
- also make these changes to components in the `upcoming-components` directory (I'm focusing on the components in `components` for right now since those are the ones that will appear in storybook)

#### What to look for when reviewing this PR:
I'm especially looking for feedback on:
- the wording of the copy about how these components are in-progress
- whether any of these components are actually mature and should not have the beta text

### Test Plan:
Verify these comments are appearing in storybook as expected.

### CODE REVIEW

**Review by anniehu4 — APPROVED** [review]
wording LGTM! thanks for improving docstring comments also ❤️ 

wonder if it's worth not marking components for the next release as BETA. or we can remove the comment as the release comes up 🤷‍♀️

**Comment by dierat** [comment]
> wonder if it's worth not marking components for the next release as BETA. or we can remove the comment as the release comes up 🤷‍♀️

@anniehu4 For the "next release", do you mean 0.21.0? Are you thinking we would remove the beta info on all the components that would be exported in the index file in that publish?

My thinking was that the components that are in-progress for a pilot, but not really intended for broad use yet, would have the beta tag/comments, so that would include the CAD components until the pilot is finished on the EDS side and we stop making big changes on those.

**Comment by anniehu4** [comment]
> For the "next release", do you mean 0.21.0? Are you thinking we would remove the beta info on all the components that would be exported in the index file in that publish?

My thinking was that the components that are in-progress for a pilot, but not really intended for broad use yet, would have the beta tag/comments, so that would include the CAD components until the pilot is finished on the EDS side and we stop making big changes on those.

I was thinking this release: https://app.shortcut.com/czi-edu/story/196002/clarify-the-list-of-components-included-in-the-first-release, which in my head has been `v1.0.0` (when new colors & type sizes go in) 😅  your thinking makes sense though

**Comment by dierat** [comment]
> I was thinking this release: https://app.shortcut.com/czi-edu/story/196002/clarify-the-list-of-components-included-in-the-first-release, which in my head has been `v1.0.0` (when new colors & type sizes go in) 😅 your thinking makes sense though

I'll go ahead and merge this for now, and we can remove the beta stuff whenever it feels appropriate whether that's v1.0.0 or later 👍

**Pull request merged**
