### PR TITLE
chore(deps): update all non-major dependencies

### PR DESCRIPTION
**Pull request by czi-developer-foundations**
This PR contains the following updates:

| Package | Type | Change |
|---|---|---|
| [@babel/preset-env](https://babel.dev/docs/en/next/babel-preset-env) ([source](https://togithub.com/babel/babel)) | devDependencies | [`^7.23.8` -> `^7.23.9`](https://renovatebot.com/diffs/npm/@babel%2fpreset-env/7.23.8/7.23.9) |
| [@commitlint/cli](https://commitlint.js.org/) ([source](https://togithub.com/conventional-changelog/commitlint)) | devDependencies | [`^18.4.4` -> `^18.6.0`](https://renovatebot.com/diffs/npm/@commitlint%2fcli/18.4.4/18.6.0) |
| [@commitlint/config-conventional](https://commitlint.js.org/) ([source](https://togithub.com/conventional-changelog/commitlint)) | devDependencies | [`^18.4.4` -> `^18.6.0`](https://renovatebot.com/diffs/npm/@commitlint%2fconfig-conventional/18.4.4/18.6.0) |
| @&#8203;omlet/cli | devDependencies | [`^1.2.2` -> `^1.3.2`](https://renovatebot.com/diffs/npm/@omlet%2fcli/1.2.2/1.3.2) |
| [@storybook/addon-a11y](https://togithub.com/storybookjs/storybook/tree/next/code/addons/a11y) ([source](https://togithub.com/storybookjs/storybook)) | devDependencies | [`^7.6.10` -> `^7.6.12`](https://renovatebot.com/diffs/npm/@storybook%2faddon-a11y/7.6.10/7.6.12) |
| [@storybook/addon-essentials](https://togithub.com/storybookjs/storybook/tree/next/code/addons/essentials) ([source](https://togithub.com/storybookjs/storybook)) | devDependencies | [`^7.6.10` -> `^7.6.12`](https://renovatebot.com/diffs/npm/@storybook%2faddon-essentials/7.6.10/7.6.12) |
| [@storybook/addon-interactions](https://togithub.com/storybookjs/storybook/tree/next/code/addons/interactions) ([source](https://togithub.com/storybookjs/storybook)) | devDependencies | [`^7.6.10` -> `^7.6.12`](https://renovatebot.com/diffs/npm/@storybook%2faddon-interactions/7.6.10/7.6.12) |
| [@storybook/addon-links](https://togithub.com/storybookjs/storybook/tree/next/code/addons/links) ([source](https://togithub.com/storybookjs/storybook)) | devDependencies | [`^7.6.10` -> `^7.6.12`](https://renovatebot.com/diffs/npm/@storybook%2faddon-links/7.6.10/7.6.12) |
| [@storybook/react](https://togithub.com/storybookjs/storybook/tree/next/code/renderers/react) ([source](https://togithub.com/storybookjs/storybook)) | devDependencies | [`^7.6.10` -> `^7.6.12`](https://renovatebot.com/diffs/npm/@storybook%2freact/7.6.10/7.6.12) |
| [@storybook/react-webpack5](https://togithub.com/storybookjs/storybook/tree/next/code/frameworks/react-webpack5) ([source](https://togithub.com/storybookjs/storybook)) | devDependencies | [`^7.6.10` -> `^7.6.12`](https://renovatebot.com/diffs/npm/@storybook%2freact-webpack5/7.6.10/7.6.12) |
| [@testing-library/jest-dom](https://togithub.com/testing-library/jest-dom) | devDependencies | [`^6.2.0` -> `^6.4.1`](https://renovatebot.com/diffs/npm/@testing-library%2fjest-dom/6.2.0/6.4.1) |
| [@testing-library/react](https://togithub.com/testing-library/react-testing-library) | devDependencies | [`^14.1.2` -> `^14.2.1`](https://renovatebot.com/diffs/npm/@testing-library%2freact/14.1.2/14.2.1) |
| [@types/jest](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | [`^29.5.11` -> `^29.5.12`](https://renovatebot.com/diffs/npm/@types%2fjest/29.5.11/29.5.12) |
| [@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | [`^20.11.5` -> `^20.11.16`](https://renovatebot.com/diffs/npm/@types%2fnode/20.11.5/20.11.16) |
| [@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | [`^18.2.48` -> `^18.2.51`](https://renovatebot.com/diffs/npm/@types%2freact/18.2.48/18.2.51) |
| [react-focus-lock](https://togithub.com/theKashey/react-focus-lock) | dependencies | [`^2.9.6` -> `^2.9.7`](https://renovatebot.com/diffs/npm/react-focus-lock/2.9.6/2.9.7) |
| [rollup](https://rollupjs.org/) ([source](https://togithub.com/rollup/rollup)) | devDependencies | [`^4.9.5` -> `^4.9.6`](https://renovatebot.com/diffs/npm/rollup/4.9.5/4.9.6) |
| [storybook](https://togithub.com/storybookjs/storybook/tree/next/code/lib/cli) ([source](https://togithub.com/storybookjs/storybook)) | devDependencies | [`^7.6.10` -> `^7.6.12`](https://renovatebot.com/diffs/npm/storybook/7.6.10/7.6.12) |
| [ts-jest](https://kulshekhar.github.io/ts-jest) ([source](https://togithub.com/kulshekhar/ts-jest)) | devDependencies | [`^29.1.1` -> `^29.1.2`](https://renovatebot.com/diffs/npm/ts-jest/29.1.1/29.1.2) |
| [yarn](https://togithub.com/yarnpkg/berry) | packageManager | [`4.0.2` -> `4.1.0`](https://renovatebot.com/diffs/npm/yarn/4.0.2/4.1.0) |

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by booc0mtaco** [comment]
`commitlint` has some new breaking change, but doesn't seem to be flagged properly?

```
found invalid rule names: header-trim. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, subject-exclamation-mark, trailer-exists, type-case, type-empty, type-enum, type-max-length, type-min-length
RangeError: Found invalid rule names: header-trim. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, subject-exclamation-mark, trailer-exists, type-case, type-empty, type-enum, type-max-length, type-min-length```

**Comment by jeremiah-clothier** [comment]
> `commitlint` has some new breaking change, but doesn't seem to be flagged properly?
> 
> ```
> found invalid rule names: header-trim. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, subject-exclamation-mark, trailer-exists, type-case, type-empty, type-enum, type-max-length, type-min-length
> RangeError: Found invalid rule names: header-trim. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, subject-exclamation-mark, trailer-exists, type-case, type-empty, type-enum, type-max-length, type-min-length```
> ```

It looks like the issue is coming from our github action `wagoid/commitlint-github-action@v5`. `yarn commitlint` works locally. I'm going to try and replace that outdated action with our own steps that invoke `commitlint`

**Comment by jeremiah-clothier** [comment]
> `commitlint` has some new breaking change, but doesn't seem to be flagged properly?
> 
> ```
> found invalid rule names: header-trim. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, subject-exclamation-mark, trailer-exists, type-case, type-empty, type-enum, type-max-length, type-min-length
> RangeError: Found invalid rule names: header-trim. Supported rule names are: body-case, body-empty, body-full-stop, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, subject-exclamation-mark, trailer-exists, type-case, type-empty, type-enum, type-max-length, type-min-length```
> ```

@booc0mtaco It looks like the issue is coming from our github action `wagoid/commitlint-github-action@v5`. `yarn commitlint` works locally. I'm going to try and replace that outdated action with our own steps that invoke `commitlint`

**Comment by jeremiah-clothier** [comment]
Closing for now, should be resolved when #1845 merges

**Pull request closed without merging**
