### PR TITLE
refactor!: remove deprecated dropdown

### PR DESCRIPTION
**Pull request by jinlee93**
### Summary:
- removes dropdown components
- usages were removed in #1645 #1646 #1647

### Test Plan:

- [x] CI tests / new tests are not applicable
  - CI tests pass

### CODE REVIEW

**Comment by booc0mtaco** [comment]
don't forget to add `!` to mark as major. This will be some great cleanup for our next major

**Comment by jeremiah-clothier** [comment]
@jinlee93 is this a duplicate PR from some of the recent component cleanup work?

**Comment by jinlee93** [comment]
> @jinlee93 is this a duplicate PR from some of the recent component cleanup work?

It is not... it's part of it

**Review by booc0mtaco — APPROVED** [review]
🧹

**Pull request merged**
