### PR TITLE
fix(typography): add missing eds-font-size-20

### PR DESCRIPTION
**Pull request by booc0mtaco**
### Summary:

- this size was referenced in code, but not defined as a token or variable.
- add it in after cross-checking with the related design
- Verify the sizing logic (1rem = 16px/16px) for font-size 20px

### Test Plan:

- [ ] Wrote [automated tests](https://czi.atlassian.net/wiki/x/Hbl1H)
- [ ] CI tests / new tests are not applicable
- [ ] Manually tested my changes, but I want to keep the details secret
- [x] Manually tested my changes, and here are the details:
  - verify breakpoint appears properly
  - verify the token and css variable is defined

### CODE REVIEW

**Comment by booc0mtaco** [comment]
Screenshot 2023-04-11 at 16 24 41
Screenshot 2023-04-11 at 16 24 28

**Review by jinlee93 — APPROVED** [review]
Weird those snaps were affected but the font size changes makes sense

**Comment by booc0mtaco** [comment]
@jinlee93 turns out those snaps had bugs in them 🐛. at full viewport, the percentage signs and the "/ XX" were supposed to be smaller. Those snaps were using the preset-003 which had the missing font size at that breakpoint. So this fixes that too :)

**Comment by booc0mtaco** [comment]
Screenshot 2023-04-11 at 16 35 18

**Pull request merged**
