### PR TITLE
Update some docs about publishing

### PR DESCRIPTION
**Pull request by ahuth**
### Summary:

Update some docs about publishing

### Test Plan:

nada

### CODE REVIEW

**Review by dierat — APPROVED** [review]
Nice!

**Comment by jinlee93** [comment]
If you don't mind could you also update the morningstar link to https://designsystem.morningstar.com/getting-started/versioning-and-breaking-changes/ in line 9 of `PUBLISHING.md`?

**Review by booc0mtaco — APPROVED** [review]
👍

**Review by jinlee93 — APPROVED** [review]
Thanks!

**Pull request merged**
