### PR TITLE
chore(deps): update all non-major dependencies

### PR DESCRIPTION
**Pull request by czi-frontend-infra**
This PR contains the following updates:

| Package | Type | Change |
|---|---|---|
| [@chanzuckerberg/axe-storybook-testing](https://togithub.com/chanzuckerberg/axe-storybook-testing) | devDependencies | [`^6.3.0` -> `^6.3.1`](https://renovatebot.com/diffs/npm/@chanzuckerberg%2faxe-storybook-testing/6.3.0/6.3.1) |
| [@chanzuckerberg/eslint-config-edu-ts](https://togithub.com/chanzuckerberg/frontend-libs/blob/main/packages/eslint-config-edu-ts) ([source](https://togithub.com/chanzuckerberg/frontend-libs)) | devDependencies | [`^1.0.7` -> `^1.0.9`](https://renovatebot.com/diffs/npm/@chanzuckerberg%2feslint-config-edu-ts/1.0.7/1.0.9) |
| [@chanzuckerberg/eslint-plugin-stories](https://togithub.com/chanzuckerberg/frontend-libs/blob/main/packages/eslint-plugin-stories) ([source](https://togithub.com/chanzuckerberg/frontend-libs)) | devDependencies | [`^3.2.12` -> `^3.2.14`](https://renovatebot.com/diffs/npm/@chanzuckerberg%2feslint-plugin-stories/3.2.12/3.2.14) |
| [@chanzuckerberg/story-utils](https://togithub.com/chanzuckerberg/frontend-libs/blob/main/packages/story-utils) ([source](https://togithub.com/chanzuckerberg/frontend-libs)) | devDependencies | [`^3.0.12` -> `^3.0.14`](https://renovatebot.com/diffs/npm/@chanzuckerberg%2fstory-utils/3.0.12/3.0.14) |
| [@commitlint/cli](https://commitlint.js.org/) ([source](https://togithub.com/conventional-changelog/commitlint)) | devDependencies | [`^17.5.1` -> `^17.6.1`](https://renovatebot.com/diffs/npm/@commitlint%2fcli/17.5.1/17.6.1) |
| [@commitlint/config-conventional](https://commitlint.js.org/) ([source](https://togithub.com/conventional-changelog/commitlint)) | devDependencies | [`^17.4.4` -> `^17.6.1`](https://renovatebot.com/diffs/npm/@commitlint%2fconfig-conventional/17.4.4/17.6.1) |
| [@headlessui/react](https://togithub.com/tailwindlabs/headlessui) | dependencies | [`^1.7.13` -> `^1.7.14`](https://renovatebot.com/diffs/npm/@headlessui%2freact/1.7.13/1.7.14) |
| [@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | [`^18.0.31` -> `^18.0.35`](https://renovatebot.com/diffs/npm/@types%2freact/18.0.32/18.0.35) |
| [chromatic](https://www.chromatic.com) ([source](https://togithub.com/chromaui/chromatic-cli)) | devDependencies | [`^6.17.2` -> `^6.17.3`](https://renovatebot.com/diffs/npm/chromatic/6.17.2/6.17.3) |
| [eslint](https://eslint.org) ([source](https://togithub.com/eslint/eslint)) | devDependencies | [`^8.37.0` -> `^8.38.0`](https://renovatebot.com/diffs/npm/eslint/8.37.0/8.38.0) |
| [eslint-plugin-testing-library](https://togithub.com/testing-library/eslint-plugin-testing-library) | devDependencies | [`^5.10.2` -> `^5.10.3`](https://renovatebot.com/diffs/npm/eslint-plugin-testing-library/5.10.2/5.10.3) |
| [lint-staged](https://togithub.com/okonet/lint-staged) | devDependencies | [`^13.2.0` -> `^13.2.1`](https://renovatebot.com/diffs/npm/lint-staged/13.2.0/13.2.1) |
| [stylelint](https://stylelint.io) ([source](https://togithub.com/stylelint/stylelint)) | devDependencies | [`^15.3.0` -> `^15.4.0`](https://renovatebot.com/diffs/npm/stylelint/15.3.0/15.4.0) |
| [ts-jest](https://kulshekhar.github.io/ts-jest) ([source](https://togithub.com/kulshekhar/ts-jest)) | devDependencies | [`^29.0.5` -> `^29.1.0`](https://renovatebot.com/diffs/npm/ts-jest/29.0.5/29.1.0) |

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by booc0mtaco** [comment]
@ahuth @jinlee93 do you know how to re-start this? I think we can pick up `story-utils` at 4.0, but ... i guess this wouldn't prompt to do that update?

**Comment by ahuth** [comment]
I think this is configured to do only non-major version updates, so it won't pick up v4. May have to do that manually.

v4 is for Storybook 7, though. So I think 3.0.13 is what you want (that's the fixed version for Storybook 6).

**Comment by jinlee93** [comment]
Yup, renovate is configured for non major bumps. Think we should upgrade to sb7 and story-utils to v4 separately as renovate will continue to failing prs

**Comment by booc0mtaco** [comment]
@jinlee93 @ahuth looks like we are picking up story-utils .14, and there's a remaining flaky test with modal (which is likely one of the tests I unskipped). I think we are good to go on this bump now. Thanks!

**Comment by booc0mtaco** [comment]
Updating the snapshots related to this fix: https://github.com/tailwindlabs/headlessui/pull/2347

**Review by jinlee93 — APPROVED** [review]
@booc0mtaco thanks for the snap updates

**Pull request merged**
