### PR TITLE
docs(Accordion): add implementation example for accordion, icon, text

### PR DESCRIPTION
**Pull request by booc0mtaco**
### Summary:

Test and document compositions using `Accordion`, `Icon`, and `Text` to customize headers.

### Test Plan:

- [x] Wrote [automated tests](https://czi.atlassian.net/wiki/x/Hbl1H)
- [ ] CI tests / new tests are not applicable
- [ ] Manually tested my changes, but I want to keep the details secret
- [ ] Manually tested my changes, and here are the details:
  - Create an [alpha publish](https://github.com/chanzuckerberg/edu-design-system/blob/main/docs/PUBLISHING.md#alpha-release) and try out in `edu-stack` or `traject` as a sanity check if changes affect build or deploy, or are breaking, such as token changes, widely used component updates, hooks changes, and major dependency upgrades.

### CODE REVIEW

**Comment by booc0mtaco** [comment]
Screenshot 2023-09-25 at 16 55 42

**Comment by booc0mtaco** [comment]
Screenshot 2023-09-26 at 10 15 03

**Comment by booc0mtaco** [comment]
Note: this is currently doing that thing where it shows `<No Display Name>`

**Review by ahuth — APPROVED** [review]

**Comment by booc0mtaco** [comment]
Added in the source code to name the subcomponents. For some reason, the names made it all the way thru in local dev, but change to `<No Display Name />` on the storybook version. 🤔

**Pull request merged**
