### PR TITLE
chore(deps): update all non-major dependencies

### PR DESCRIPTION
**Pull request by czi-developer-foundations**
This PR contains the following updates:

| Package | Type | Change |
|---|---|---|
| [@rollup/plugin-typescript](https://togithub.com/rollup/plugins/tree/master/packages/typescript/#readme) ([source](https://togithub.com/rollup/plugins)) | devDependencies | [`^11.1.0` -> `^11.1.1`](https://renovatebot.com/diffs/npm/@rollup%2fplugin-typescript/11.1.0/11.1.1) |
| [@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | [`^18.16.4` -> `^18.16.8`](https://renovatebot.com/diffs/npm/@types%2fnode/18.16.5/18.16.8) |
| [@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | [`^18.2.5` -> `^18.2.6`](https://renovatebot.com/diffs/npm/@types%2freact/18.2.6/18.2.6) |
| [@types/react-dom](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | devDependencies | [`^18.2.3` -> `^18.2.4`](https://renovatebot.com/diffs/npm/@types%2freact-dom/18.2.4/18.2.4) |
| [eslint](https://eslint.org) ([source](https://togithub.com/eslint/eslint)) | devDependencies | [`^8.39.0` -> `^8.40.0`](https://renovatebot.com/diffs/npm/eslint/8.39.0/8.40.0) |
| [eslint-plugin-testing-library](https://togithub.com/testing-library/eslint-plugin-testing-library) | devDependencies | [`^5.10.3` -> `^5.11.0`](https://renovatebot.com/diffs/npm/eslint-plugin-testing-library/5.10.3/5.11.0) |
| [rollup](https://rollupjs.org/) ([source](https://togithub.com/rollup/rollup)) | devDependencies | [`^3.21.5` -> `^3.21.6`](https://renovatebot.com/diffs/npm/rollup/3.21.5/3.21.6) |

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by jinlee93** [comment]
Could this be related to the github/npm publishes or the edu-libs being private?

**Comment by booc0mtaco** [comment]
> Could this be related to the github/npm publishes or the edu-libs being private?

@jinlee93 I think this was some transient network issue :S i'm gonna force it using "rebase!" in the title

**Comment by timzchang** [comment]
80% sure checks are failing bc of the renovate bot failing to add the changed `yarn.lock` 

> The artifact failure details are included below:
>
> File name: yarn.lock
> curl: (18) transfer closed with 11619912 bytes remaining to read
> Download failed: https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.xz

Then the `--immutable` flag in github actions causing the install step to fail.

Not super sure how renovate works so hoping that rebasing also adds the lock file? cc @jeremiah-clothier double checking

**Comment by jeremiah-clothier** [comment]
> 80% sure checks are failing bc of the renovate bot failing to add the changed `yarn.lock`
> 
> > The artifact failure details are included below:
> > File name: yarn.lock
> > curl: (18) transfer closed with 11619912 bytes remaining to read
> > Download failed: https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.xz
> 
> Then the `--immutable` flag in github actions causing the install step to fail.
> 
> Not super sure how renovate works so hoping that rebasing also adds the lock file? cc @jeremiah-clothier double checking

[Rerunning the workflow](https://github.com/chanzuckerberg/edu-design-system/actions/workflows/update-dependencies.yml) so we'll see what happens

**Comment by booc0mtaco** [comment]
We are no longer seeing Open Sans get loaded in the snapshots, or in dev. Possibly related to #1611 ... somehow?

https://chanzuckerberg.github.io/edu-design-system/?path=/story/design-tokens-tier-1-definitions--typography-tokens

Will investigate tomorrow

**Comment by booc0mtaco** [comment]
The font issue here is unrelated, so will unblock this by getting #1615 merged in first, then rebasing here

**Review by booc0mtaco — APPROVED** [review]

**Pull request merged**
