### PR TITLE
Release v13.0.0

### PR DESCRIPTION
**Pull request by booc0mtaco**
## [13.0.0](https://github.com/chanzuckerberg/edu-design-system/compare/v12.4.2...v13.0.0) (2023-08-14)

Review the text next to each breaking change for suggestions on how to transform your existing code for compatibility with this version.

### ⚠ BREAKING CHANGES

<details>
<summary><strong>link:</strong> remove text-link tokens for link t3 tokens (#1639)</summary>

The following tokens have been removed, and their usages have been replaced:

* `--eds-theme-color-text-link-brand`
* `--eds-theme-color-text-link-neutral`

New tokens were added in 12.x versions, and are proper tier-2 tokens, which supersede these. For reference they are:

* `--eds-theme-color-text-neutral-*` (includes, `neutral`, `strong`, `default`, and `default-inverse`)
* `--eds-theme-color-text-brand-default`

Check the relevant figma files and ZH documentation on what values should be set for the tokens above
</details>

<details>
<summary><strong>colors:</strong> remove old colors and convert to input and show figma token (#1711)</summary>

Many color tokens were long-ago deprecated. They are now being removed to simplify the token set and align with the latest foundation and component files. 

This includes the following:

* `--eds-color-highlight-*`
* `--eds-color-info-*`

If you spot any of these in design files, consult with the design team about cleanup.

</details>

<details>
<summary>remove deprecated dropdown (#1657)</summary>

The `Dropdown` component is now being removed, to be replaced by the more feature-rich `Menu` and `Select` components. 

</details>

<details>
<summary><strong>banner:</strong> remove component (#1702)</summary>

The `Banner` component was not available in design, as it had been removed some time ago. So we remove it in this release. No designs should use this component. Instead, refer to the `InlineNotification` or `Toast` components.

</details>

<details>
<summary>remove legacy tokens and typography mixins (#1709)</summary>

We remove the remaining `legacy` tokens from EDS, and the legacy Typography `@mixins`. Examples include:

* `--legacy-color-*`
* `--legacy-size-*`

These were not being used in any internal components, and should not be used in any product-specific recipes. If they were, work with design to find a supported alternative for those tokens.

Along with those removals, we replace all calls to mixins with equivalent `font:` CSS properties. The mixins were NOT exported, but this does enable the use of `typography` tokens in custom recipes if needed.

```diff
-@mixin eds-typography-preset-001;
+font: var(--eds-typography-preset-001);
```

</details>

<details>
<summary><strong>Grid:</strong> remove top-level sub-component(s) (#1703)</summary>

If you are importing any `Grid` sub-components  in your code, you can remove the import

```diff
-import GridItem from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<GridItem>{...}</GridItem>
+<Grid.Item>{...}</Grid.Item>
```

</details>

<details>
<summary><strong>dragdrop:</strong> remove top level subcomponents (#1697)</summary>

If you are importing any `DragDrop` sub-components  in your code, you can remove the import

```diff
-import DragDropContainerHeader from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<DragDropContainerHeader>{...}</DragDropContainerHeader>
+<DragDrop.ContainerHeader>{...}</DragDrop.ContainerHeader>
```

</details>

<details>
<summary><strong>Fieldset:</strong> remove top-level sub-component(s) (#1695)</summary>

If you are importing any `Fieldset` sub-components  in your code, you can remove the import

```diff
-import FieldsetItems from '@chanzuckerberg/eds';
-import FieldsetLegend from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<FieldsetItems>{...}</FieldsetItems>
+<Fieldset.Items>{...}</Fieldset.Items>
-<FieldsetLegend>{...}</FieldsetLegend>
+<Fieldset.Legend>{...}</Fieldset.Legend>
```

</details>

<details>
<summary><strong>HorizontalStepper:</strong> remove top-level sub-component(s) (#1696)</summary>

If you are importing any `HorizontalStepper` sub-components  in your code, you can remove the import

```diff
-import HorizontalStep from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<HorizontalStep>{...}</HorizontalStep>
+<HorizontalStepper.Step>{...}</HorizontalStepper.Step>
```

</details>

<details>
<summary><strong>Card:</strong> remove top-level sub-component(s) (#1692)</summary>

If you are importing any `Card` sub-components  in your code, you can remove the import

```diff
-import CardHeader from '@chanzuckerberg/eds';
-import CardBody from '@chanzuckerberg/eds';
-import CardFooter from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<CardHeader>{...}</CardHeader>
+<Card.Header>{...}</Card.Header>
-<CardBody>{...}</CardBody>
+<Card.Body>{...}</Card.Body>
-<CardFooter>{...}</CardFooter>
+<Card.Footer>{...}</Card.Footer>
```

</details>

<details>
<summary><strong>checkbox:</strong> remove top level subcomponents (#1693)</summary>

If you are importing any `Checkbox` sub-components  in your code, you can remove the import

```diff
-import CheckboxInput from '@chanzuckerberg/eds';
-import CheckboxLabel from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<CheckboxInput>{...}</CheckboxInput>
+<Checkbox.Input>{...}</Checkbox.Input>
-<CheckboxLabel>{...}</CheckboxLabel>
+<Checkbox.Label>{...}</Checkbox.Label>
```

</details>

<details>
<summary><strong>radio:</strong> remove top level subcomponents (#1690)</summary>

If you are importing any `Radio` sub-components  in your code, you can remove the import

```diff
-import RadioInput from '@chanzuckerberg/eds';
-import RadioLabel from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<RadioInput>{...}</RadioInput>
+<Radio.Input>{...}</Radio.Input>
-<RadioLabel>{...}</RadioLabel>
+<Radio.Label>{...}</Radio.Label>
```

</details>

<details>
<summary><strong>DataBar:</strong> remove top-level sub-component(s) (#1686)</summary>

If you are importing any `DataBar` sub-components  in your code, you can remove the import

```diff
-import DataBarSegment from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<DataBarSegment>{...}</DataBarSegment>
+<DataBar.Segment>{...}</DataBar.Segment>

```

</details>

<details>
<summary><strong>Modal:</strong> remove top-level sub-component(s) (#1689)</summary>

If you are importing any `Modal` sub-components  in your code, you can remove the import

```diff
-import ModalTitle from '@chanzuckerberg/eds';
-import MobalBody from '@chanzuckerberg/eds';
-import ModalFooter from '@chanzuckerberg/eds';
-import ModalHeader from '@chanzuckerberg/eds';
-import ModalStepper from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<ModalTitle>{...}</ModalTitle>
+<Modal.Title>{...}</Modal.Title>
-<ModalBody>{...}</ModalBody>
+<Modal.Body>{...}</Modal.Body>
-<ModalFooter>{...}</ModalFooter>
+<Modal.Footer>{...}</Modal.Footer>
-<ModalHeader>{...}</ModalHeader>
+<Modal.Header>{...}</Modal.Header>
-<ModalStepper>{...}</ModalStepper>
+<Modal.Stepper>{...}</Modal.Stepper>
```

</details>

<details>
<summary><strong>searchbar:</strong> remove top level subcomponents (#1687)</summary>

If you are importing the `SearchButton` or `SearchField` in your code, you can remove the import

```diff
- import SearchButton from '@chanzuckerberg/eds';
- import SearchField from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<SearchButton>{...}</SearchButton>
+<SearchBar.Button>{...}</SearchBar.Button>
-<SearchField>{...}</SearchField>
+<SearchBar.Field>{...}</SearchBar.Field>
```

</details>

<details>
<summary><strong>table:</strong> remove top-level sub-components (#1685)</summary>

If you are importing any `Table` sub-components  in your code, you can remove the import

```diff
-import TableRow from '@chanzuckerberg/eds';
-import TableCell from '@chanzuckerberg/eds';
-import TableBody from '@chanzuckerberg/eds';
-import TableCaption from '@chanzuckerberg/eds';
-import TableHeader from '@chanzuckerberg/eds';
-import TableHeaderCell from '@chanzuckerberg/eds';
-import TableFooter from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<TableRow>{...}</TableRow>
+<Table.Row>{...}</Table.Row>
-<TableBody>{...}</TableBody>
+<Table.Body>{...}</Table.Body>
-<TableFooter>{...}</TableFooter>
+<Table.Footer>{...}</Table.Footer>
-<TableHeader>{...}</TableHeader>
+<Table.Header>{...}</Table.Header>
-<TableHeaderCell>{...}</TableHeaderCell>
+<Table.HeaderCell>{...}</Table.HeaderCell>
-<TableCaption>{...}</TableCaption>
+<Table.Caption>{...}</Table.Caption>
-<TableCell>{...}</TableCell>
+<Table.Cell>{...}</Table.Cell>
```

</details>

<details>
<summary><strong>toolbar:</strong>remove component (#1683)</summary>

`Toolbar` was removed, as it had no corresponding designs, and prescribed a layout that is more likely to be product specific. If there is a strong design and rationale for a new toolbar, it may re-emerge as a standalone component, composed of various EDS sub-components.

If using toolbar, consider replacing with equivalent TailwindCSS Layout classes:

```diff
-<Toolbar className="!mb-4" variant="bare"></Toolbar>
+<div className="mb-4 flex items-center gap-4"></div>
```

```diff
-<ToolbarItem></ToolbarItem>
+<div className="ml-auto"></div>
```

</details>

<details>
<summary><strong>Breadcrumbs:</strong> remove top-level sub-component (#1680)</summary>

If you are importing the `BreadcrumbsItem` in your code, you can remove the import

```diff
- import BreadcrumbsItem from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<BreadcrumbsItem>{...}</BreadcrumbsItem>
+<Breadcrumbs.Item>{...}</Breadcrumbs.Item>
```
</details>

<details>
<summary><strong>timelinenav:</strong> remove top-level sub-component (#1681)</summary>

If you are importing the `TimelineNavPanel` in your code, you can remove the import

```diff
- import TimelineNavPanel from '@chanzuckerberg/eds';
```

... and replace references to the sub-component with the following:
```diff
-<TimelineNavPanel>{...}</TimelineNavPanel>
+<TimelineNav.Panel>{...}</TimelineNav.Panel>
```

</details>

### Features

* **Breadcrumbs:** remove top-level sub-component ([#1680](https://github.com/chanzuckerberg/edu-design-system/issues/1680)) ([669081d](https://github.com/chanzuckerberg/edu-design-system/commit/669081dce402c0f84799ef17af6c8e05ccc4c37a))
* **Card:** remove top-level sub-component(s) ([#1692](https://github.com/chanzuckerberg/edu-design-system/issues/1692)) ([7ec01f4](https://github.com/chanzuckerberg/edu-design-system/commit/7ec01f434e5c2d58bc0b95f5f3c7ebc318393bf2))
* **checkbox:** remove top level subcomponents ([#1693](https://github.com/chanzuckerberg/edu-design-system/issues/1693)) ([87b12e8](https://github.com/chanzuckerberg/edu-design-system/commit/87b12e8ee5237ae99b037b3285364a363d4f2749))
* **DataBar:** remove top-level sub-component(s) ([#1686](https://github.com/chanzuckerberg/edu-design-system/issues/1686)) ([b4b9276](https://github.com/chanzuckerberg/edu-design-system/commit/b4b9276fb5115542a1e659d4d13a830aa5e7d4b0))
* **dragdrop:** remove top level subcomponents ([#1697](https://github.com/chanzuckerberg/edu-design-system/issues/1697)) ([b4fd00c](https://github.com/chanzuckerberg/edu-design-system/commit/b4fd00ca3daea679099a7fe073c03b476e9fbde2))
* **Fieldset:** remove top-level sub-component(s) ([#1695](https://github.com/chanzuckerberg/edu-design-system/issues/1695)) ([0c8280d](https://github.com/chanzuckerberg/edu-design-system/commit/0c8280d18b18f684d772a9fe3346ede375fdbefe))
* **Grid:** remove top-level sub-component(s) ([#1703](https://github.com/chanzuckerberg/edu-design-system/issues/1703)) ([c8925c9](https://github.com/chanzuckerberg/edu-design-system/commit/c8925c96fd219b145d56dbe270020b26e7ff97d0))
* **HorizontalStepper:** remove top-level sub-component(s) ([#1696](https://github.com/chanzuckerberg/edu-design-system/issues/1696)) ([188fd99](https://github.com/chanzuckerberg/edu-design-system/commit/188fd992c28c34c370debd59b4db8cb82ca9752b))
* **Layout:** mark layout components as deprecated ([#1700](https://github.com/chanzuckerberg/edu-design-system/issues/1700)) ([930a369](https://github.com/chanzuckerberg/edu-design-system/commit/930a369143abca25728d0f03e236aeb244781d6e))
* **Modal:** remove top-level sub-component(s) ([#1689](https://github.com/chanzuckerberg/edu-design-system/issues/1689)) ([8743e62](https://github.com/chanzuckerberg/edu-design-system/commit/8743e627bb70eed44f13b56efcbe1c77deac0a21))
* **radio:** remove top level subcomponents ([#1690](https://github.com/chanzuckerberg/edu-design-system/issues/1690)) ([82da617](https://github.com/chanzuckerberg/edu-design-system/commit/82da6178bd61657e31595788249a53c69aef6b56))
* remove legacy tokens and typography mixins ([#1709](https://github.com/chanzuckerberg/edu-design-system/issues/1709)) ([ec3e819](https://github.com/chanzuckerberg/edu-design-system/commit/ec3e81972e7d6952a227f6c01cedcc25aee5f9c4))
* **searchbar:** remove top level subcomponents ([#1687](https://github.com/chanzuckerberg/edu-design-system/issues/1687)) ([d13bb6c](https://github.com/chanzuckerberg/edu-design-system/commit/d13bb6cd643b4ed87fadbe0f168cf763f07157c3))
* **table:** remove top-level sub-components ([#1685](https://github.com/chanzuckerberg/edu-design-system/issues/1685)) ([742a530](https://github.com/chanzuckerberg/edu-design-system/commit/742a530babe97f507582f31b84bcbf6eb78591e8))
* **timelinenav:** remove top-level sub-component ([#1681](https://github.com/chanzuckerberg/edu-design-system/issues/1681)) ([f46eca7](https://github.com/chanzuckerberg/edu-design-system/commit/f46eca76ba44088d23050fde7f659f3f7e23e1e8))

### Bug Fixes

* **Avatar:** support display names using emoji and multi-byte ([#1716](https://github.com/chanzuckerberg/edu-design-system/issues/1716)) ([1294022](https://github.com/chanzuckerberg/edu-design-system/commit/1294022658b48e709413b5080fc45a0bbc126268))
* update token exports ([#1722](https://github.com/chanzuckerberg/edu-design-system/issues/1722)) ([982c55f](https://github.com/chanzuckerberg/edu-design-system/commit/982c55f122f96cf68bddd77955540dd236a000cc))

* **banner:** remove component ([#1702](https://github.com/chanzuckerberg/edu-design-system/issues/1702)) ([356550c](https://github.com/chanzuckerberg/edu-design-system/commit/356550c699a3fd549315f06fccdd569932032c4e))
* **colors:** remove old colors and convert to input and show figma token ([#1711](https://github.com/chanzuckerberg/edu-design-system/issues/1711)) ([c9a5079](https://github.com/chanzuckerberg/edu-design-system/commit/c9a5079ab2b3b61abf431d859f1ecb4a068272f9))
* **link:** remove text-link tokens for link t3 tokens ([#1639](https://github.com/chanzuckerberg/edu-design-system/issues/1639)) ([d35cfe4](https://github.com/chanzuckerberg/edu-design-system/commit/d35cfe44be0fa618f45fe2051d240e27c55f5199))
* remove deprecated dropdown ([#1657](https://github.com/chanzuckerberg/edu-design-system/issues/1657)) ([26d1694](https://github.com/chanzuckerberg/edu-design-system/commit/26d16942f9e2393312db773eb06e72fc7ab54620))
* **toolbar:** remove component ([#1683](https://github.com/chanzuckerberg/edu-design-system/issues/1683)) ([bd47899](https://github.com/chanzuckerberg/edu-design-system/commit/bd478996207ff59e4dd43c06da9711e14ecd09b4))

### CODE REVIEW

**Comment by booc0mtaco** [comment]
As a part of this release, we will annotate the release notes with guidance on how to address any breaking changes. This could be as a set of summary blocks added to the release notes, OR as a link to the EDS repo Wiki detailing migration steps from 12 to 13.

**Comment by jeremiah-clothier** [comment]
Is there anything specific to look over in this PR or since it's a collection of previously merged PRs not really?

**Comment by booc0mtaco** [comment]
> Is there anything specific to look over in this PR or since it's a collection of previously merged PRs not really?

@jeremiah-clothier I'm adding in instructions to the summary above, explaining how to resolve any of the breaking changes. Once i finish that, if you could have a look and see if those read pretty clearly, that would be most helpful :D 

For release PRs, the main thing is to verify the change log is correct and helpful

**Comment by jeremiah-clothier** [comment]
> remove

okay @booc0mtaco feel free to ping me when all the instructions are added

**Review by ahuth — APPROVED** [review]

**Pull request merged**
