### PR TITLE
docs(recipe): remove DataSummaryCard recipe

### PR DESCRIPTION
**Pull request by booc0mtaco**
### Summary:

- this recipe, as-is, only shows how one might compose a stardard card, so it is redundant
- the layout in question is mostly specific to a single project, so not general purpose
- embedding in the example page in EDS for now

### Test Plan:

- n/a

### CODE REVIEW

**Comment by booc0mtaco** [comment]
@anniehu4 @jinlee93 It appears this recipe is imported into the Student summary page. I reckon that should probably be dropped as well? By name alone, it appears too specific to be in EDS

**Review by timzchang — APPROVED** [review]
👋🏼

**Comment by jinlee93** [comment]
> @anniehu4 @jinlee93 It appears this recipe is imported into the Student summary page. I reckon that should probably be dropped as well? By name alone, it appears too specific to be in EDS

I am ok with dropping that page but would check with design. Think the point of that page where the table breaks into cards in smaller viewports is captured with the `StackedCardsToTable` recipe anyways

**Comment by booc0mtaco** [comment]
@jinlee93 yah, i opted to keep the page for now, and port over the summary cards just to keep the diff small. We can bring up pages with design over the next pairing session

**Comment by jinlee93** [comment]
@booc0mtaco Can you place the DataSummaryCard in the page itself then, since it's the only use

**Comment by booc0mtaco** [comment]
@jinlee93 done :>

**Review by jinlee93 — APPROVED** [review]

**Comment by jinlee93** [comment]
@booc0mtaco sweet thanks :D

**Pull request merged**
