### PR TITLE
Use czi/prettier-config-edu

### PR DESCRIPTION
**Pull request by jinlee93**
### Summary:
- adds prettier config for Tailwind for linted classname orders
- recommends TW vscode extension in docs
- fixes lint issues from aforementioned prettier config
### Test Plan:
- no associated lint errors

### CODE REVIEW

**Comment by jinlee93** [comment]
We can also try adding this TW prettier plugin in `prettier-config-edu`

**Comment by jinlee93** [comment]
Realized this was already part of `czi/edu-prettier-config` will just update to use that

**Review by booc0mtaco — APPROVED** [review]
LGTM

**Comment by booc0mtaco** [comment]
@jinlee93 This will only affect usage in storybook, correct?

**Comment by jinlee93** [comment]
> @jinlee93 This will only affect usage in storybook, correct?

Since this is just adding prettier to lint for TW classname orders, it shouldn't affect anything, especially since TW classnames are only being used for stories or non component / release files.

**Pull request merged**
