### PR TITLE
fix(Select): sync label design with form fields

### PR DESCRIPTION
**Pull request by booc0mtaco**
### Summary:

- remove little used helper mixin, and apply typography to labels
- add overline container to match label structure for textarea and input fields
- update snapshots
- EDS-841

### Test Plan:

- [x] Wrote [automated tests](https://czi.atlassian.net/wiki/x/Hbl1H)
- [x] CI tests / new tests are not applicable
- [ ] Manually tested my changes, but I want to keep the details secret
- [ ] Manually tested my changes, and here are the details:
  - Create an [alpha publish](https://github.com/chanzuckerberg/edu-design-system/blob/main/docs/PUBLISHING.md#alpha-release) and try out in `edu-stack` or `traject` as a sanity check if changes affect build or deploy, or are breaking, such as token changes, widely used component updates, hooks changes, and major dependency upgrades.

### CODE REVIEW

**Comment by booc0mtaco** [comment]
Screenshot 2023-02-23 at 13 07 31

**Review by jinlee93 — APPROVED** [review]
FWIW the input has an overline container since there are two elements in it spaced apart (the label and optional/required)

**Comment by booc0mtaco** [comment]
> FWIW the input has an overline container since there are two elements in it spaced apart (the label and optional/required)

Makes sense. I feel like `Select` should also be able to be marked as required? so this will set us up to implement that after chatting with design

**Comment by jinlee93** [comment]
> > FWIW the input has an overline container since there are two elements in it spaced apart (the label and optional/required)
> 
> Makes sense. I feel like `Select` should also be able to be marked as required? so this will set us up to implement that after chatting with design

Sounds good 👍

**Pull request merged**
