### PR TITLE
chore: remove upcoming components that look pretty pointless

### PR DESCRIPTION
**Pull request by schakraborty22**
### Summary:
Story ID:214001
Remove upcoming components that will never be used (and therefore we're wasting our time improving the code for those),  list of components removed:
Band
StackedBlock(This component already exists in components.)
StackedBlockBody
StackedBlockFooter
StackedBlockHeader
Tags
TagsItem
Tile
TileBody
TileHeader

### CODE REVIEW

**Comment by dierat** [comment]
https://app.shortcut.com/czi-edu/story/214001/remove-upcoming-components-that-look-pretty-pointless

**Comment by schakraborty22** [comment]
> https://app.shortcut.com/czi-edu/story/214001/remove-upcoming-components-that-look-pretty-pointless

**Comment by dierat** [comment]
This looks good to me, but I'd like a second opinion from someone else about whether it makes sense to remove these specific components (and if there are others we should remove while we're at it). I added my reasoning to why I picked these components in the ticket description: https://app.shortcut.com/czi-edu/story/214001/remove-upcoming-components-that-look-pretty-pointless

**Review by dierat — APPROVED** [review]

**Review by jinlee93 — APPROVED** [review]
Makes sense to me!

**Comment by jinlee93** [comment]
> This looks good to me, but I'd like a second opinion from someone else about whether it makes sense to remove these specific components (and if there are others we should remove while we're at it). I added my reasoning to why I picked these components in the ticket description: https://app.shortcut.com/czi-edu/story/214001/remove-upcoming-components-that-look-pretty-pointless

Thanks for the reasoning and this list. I think the list was well picked and personally thought it was on the more conservative side as I think components such as `Counter` and `Feature` could also be on the chopping block, but they do provide a use rather than slapping some tags together or text and padding ¯\\_(ツ)_/¯

**Comment by dierat** [comment]
> > This looks good to me, but I'd like a second opinion from someone else about whether it makes sense to remove these specific components (and if there are others we should remove while we're at it). I added my reasoning to why I picked these components in the ticket description: https://app.shortcut.com/czi-edu/story/214001/remove-upcoming-components-that-look-pretty-pointless
> 
> Thanks for the reasoning and this list. I think the list was well picked and personally thought it was on the more conservative side as I think components such as `Counter` and `Feature` could also be on the chopping block, but they do provide a use rather than slapping some tags together or text and padding ¯\_(ツ)_/¯

I'm fine to remove those too. `TextList` and `TextListItem` also seem kinda pointless to me. I even wonder if we should just pick out the ones that have specific functionality we would want to keep (like in `Accordion`, `FileUploadField`, and `Skeleton`) and remove the others.

**Comment by jinlee93** [comment]
> 

Yea I'm down for that. I can push up a tag for eds v5 as having the last of the `upcoming-components` if we ever need to look back as well

**Comment by jinlee93** [comment]
> > > This looks good to me, but I'd like a second opinion from someone else about whether it makes sense to remove these specific components (and if there are others we should remove while we're at it). I added my reasoning to why I picked these components in the ticket description: https://app.shortcut.com/czi-edu/story/214001/remove-upcoming-components-that-look-pretty-pointless
> > 
> > 
> > Thanks for the reasoning and this list. I think the list was well picked and personally thought it was on the more conservative side as I think components such as `Counter` and `Feature` could also be on the chopping block, but they do provide a use rather than slapping some tags together or text and padding ¯_(ツ)_/¯
> 
> I'm fine to remove those too. `TextList` and `TextListItem` also seem kinda pointless to me. I even wonder if we should just pick out the ones that have specific functionality we would want to keep (like in `Accordion`, `FileUploadField`, and `Skeleton`) and remove the others.

Yea I'm down for that. I can push up a tag for eds v5 as having the last of the `upcoming-components` if we ever need to look back as well

**Comment by schakraborty22** [comment]
> > > > This looks good to me, but I'd like a second opinion from someone else about whether it makes sense to remove these specific components (and if there are others we should remove while we're at it). I added my reasoning to why I picked these components in the ticket description: https://app.shortcut.com/czi-edu/story/214001/remove-upcoming-components-that-look-pretty-pointless
> > > 
> > > 
> > > Thanks for the reasoning and this list. I think the list was well picked and personally thought it was on the more conservative side as I think components such as `Counter` and `Feature` could also be on the chopping block, but they do provide a use rather than slapping some tags together or text and padding ¯_(ツ)_/¯
> > 
> > 
> > I'm fine to remove those too. `TextList` and `TextListItem` also seem kinda pointless to me. I even wonder if we should just pick out the ones that have specific functionality we would want to keep (like in `Accordion`, `FileUploadField`, and `Skeleton`) and remove the others.
> 
> Yea I'm down for that. Should I push up a tag for eds v5 as having the last of the `upcoming-components` in case we ever need to look back?

Sound like good idea for future reference !

**Comment by jinlee93** [comment]
Branched off https://github.com/chanzuckerberg/edu-design-system/tree/oldUpcomingComponents

**Pull request merged**
